CREATE DATABASE csdl_taxi;
CREATE DATABASE csdl_doithicong;

USE csdl_taxi
CREATE TABLE LOAI_PHUONGTIEN (
    LoaiPT INT NOT NULL,
    TenLoai VARCHAR(64) NOT NULL,
    CONSTRAINT PK_LOAI_PHUONGTIEN
        PRIMARY KEY (LoaiPT)
);

CREATE TABLE LAIXE (
    MaLX INT NOT NULL,
    Ho VARCHAR(15) NOT NULL,
    Dem VARCHAR(15),
    Ten VARCHAR(15) NOT NULL,
    NgaySinh DATE,
    SoGP CHAR(12) NOT NULL,
    HanGP DATE NOT NULL,
    CONSTRAINT PK_LAIXE
        PRIMARY KEY (MaLX)
);

CREATE TABLE PHUONGTIEN (
    LoaiPT INT NOT NULL,
    SoPT INT NOT NULL,
    BienSo CHAR(10) NOT NULL,
    NamSanXuat INT NOT NULL,
    ChuPT INT,
    TinhTrang INT NOT NULL DEFAULT 1 CHECK (TinhTrang IN (0, 1)),
    CONSTRAINT PK_PHUONGTIEN
        PRIMARY KEY (SoPT)
);

CREATE TABLE CALAMVIEC (
    MaCLV   INT      NOT NULL,
    MaLX    INT      NOT NULL,
    SoPT    INT      NOT NULL,
    BatDau  DATETIME NOT NULL,
    KetThuc DATETIME NOT NULL,
    CONSTRAINT PK_CALAMVIEC
        PRIMARY KEY (MaCLV)
);


ALTER TABLE PHUONGTIEN
    ADD CONSTRAINT FK_PT_LOAIPT
    FOREIGN KEY (LoaiPT) REFERENCES LOAI_PHUONGTIEN (LoaiPT);

ALTER TABLE PHUONGTIEN
    ADD CONSTRAINT FK_PT_CHUPT
    FOREIGN KEY (ChuPT) REFERENCES LAIXE (MaLX);

ALTER TABLE CALAMVIEC
    ADD CONSTRAINT FK_CLV_LAIXE
    FOREIGN KEY (MaLX) REFERENCES LAIXE (MaLX);

ALTER TABLE CALAMVIEC
    ADD CONSTRAINT FK_CLV_PT
    FOREIGN KEY (SoPT) REFERENCES PHUONGTIEN (SoPT);

USE csdl_doithicong;

CREATE TABLE HANG (
    HangCN    INT          NOT NULL,
    HeSoLuong DECIMAL(3,1) NOT NULL,
    CONSTRAINT PK_HANG PRIMARY KEY (HangCN),
    CONSTRAINT CK_HANG_HangCN CHECK (HangCN BETWEEN 1 AND 5)
);

CREATE TABLE DOITHICONG (
    MaDoi      INT NOT NULL,
    DoiTruong  INT,
    ThuocDonVi INT NOT NULL,
    CONSTRAINT PK_DOITHICONG PRIMARY KEY (MaDoi)
);

CREATE TABLE CONGNHAN (
    MaCN          INT         NOT NULL,
    Ho            VARCHAR(30) NOT NULL,
    Ten           VARCHAR(15) NOT NULL,
    NgaySinh      DATE,
    GioiTinh      CHAR(1)     CHECK (GioiTinh IN ('f', 'F', 'm', 'M')),
    HangCN        INT         NOT NULL,
    NgayTuyenDung DATE,
    MaDoi         INT         NOT NULL,
    CONSTRAINT PK_CONGNHAN PRIMARY KEY (MaCN)
);

CREATE TABLE CONGTRINH (
    MaCT       INT         NOT NULL,
    TenCT      VARCHAR(50) NOT NULL,
    DiaDiem    VARCHAR(50),
    DonViChinh INT         NOT NULL,
    CONSTRAINT PK_CONGTRINH PRIMARY KEY (MaCT)
);

CREATE TABLE CHAMCONG (
    MaCT       INT  NOT NULL,
    MaDoi      INT  NOT NULL,
    MaCN       INT  NOT NULL,
    NgayLamViec DATE NOT NULL,
    SoGio      FLOAT NOT NULL,
    CONSTRAINT PK_CHAMCONG PRIMARY KEY (MaCT, MaDoi, MaCN, NgayLamViec)
);

ALTER TABLE CONGNHAN
    ADD CONSTRAINT FK_CN_HANG
    FOREIGN KEY (HangCN) REFERENCES HANG (HangCN);

ALTER TABLE CONGNHAN
    ADD CONSTRAINT FK_CN_DOI
    FOREIGN KEY (MaDoi) REFERENCES DOITHICONG (MaDoi);

ALTER TABLE DOITHICONG
    ADD CONSTRAINT FK_DOI_TRUONG
    FOREIGN KEY (DoiTruong) REFERENCES CONGNHAN (MaCN);

ALTER TABLE CONGTRINH
    ADD CONSTRAINT FK_CT_DONVI
    FOREIGN KEY (DonViChinh) REFERENCES DOITHICONG (MaDoi);

ALTER TABLE CHAMCONG
    ADD CONSTRAINT FK_CC_CT
    FOREIGN KEY (MaCT) REFERENCES CONGTRINH (MaCT);

ALTER TABLE CHAMCONG
    ADD CONSTRAINT FK_CC_DOI
    FOREIGN KEY (MaDoi) REFERENCES DOITHICONG (MaDoi);

ALTER TABLE CHAMCONG
    ADD CONSTRAINT FK_CC_CN
    FOREIGN KEY (MaCN) REFERENCES CONGNHAN (MaCN);
