CREATE DATABASE csdl_taxi;

USE csdl_taxi

CREATE TABLE LOAI_PHUONGTIEN (
    LoaiPT INT NOT NULL,
    TenLoai VARCHAR(64) NOT NULL,
    CONSTRAINT PK_LOAI_PHUONGTIEN
        PRIMARY KEY (LoaiPT)
);

CREATE TABLE LAIXE (
    MaLX INT NOT NULL,
    Ho VARCHAR(15) NOT NULL,
    Dem VARCHAR(15),
    Ten VARCHAR(15) NOT NULL,
    NgaySinh DATE,
    SoGP CHAR(12) NOT NULL,
    HanGP DATE NOT NULL,
    CONSTRAINT PK_LAIXE
        PRIMARY KEY (MaLX)
);

CREATE TABLE PHUONGTIEN (
    LoaiPT INT NOT NULL,
    SoPT INT NOT NULL,
    BienSo CHAR(10) NOT NULL,
    NamSanXuat INT NOT NULL,
    ChuPT INT,
    TinhTrang INT NOT NULL DEFAULT 1 CHECK (TinhTrang IN (0, 1)),
    CONSTRAINT PK_PHUONGTIEN
        PRIMARY KEY (SoPT)
);

CREATE TABLE CALAMVIEC (
    MaCLV   INT      NOT NULL,
    MaLX    INT      NOT NULL,
    SoPT    INT      NOT NULL,
    BatDau  DATETIME NOT NULL,
    KetThuc DATETIME NOT NULL,
    CONSTRAINT PK_CALAMVIEC
        PRIMARY KEY (MaCLV)
);


ALTER TABLE PHUONGTIEN
    ADD CONSTRAINT FK_PT_LOAIPT
    FOREIGN KEY (LoaiPT) REFERENCES LOAI_PHUONGTIEN (LoaiPT);

ALTER TABLE PHUONGTIEN
    ADD CONSTRAINT FK_PT_CHUPT
    FOREIGN KEY (ChuPT) REFERENCES LAIXE (MaLX);

ALTER TABLE CALAMVIEC
    ADD CONSTRAINT FK_CLV_LAIXE
    FOREIGN KEY (MaLX) REFERENCES LAIXE (MaLX);

ALTER TABLE CALAMVIEC
    ADD CONSTRAINT FK_CLV_PT
    FOREIGN KEY (SoPT) REFERENCES PHUONGTIEN (SoPT);

INSERT INTO LOAI_PHUONGTIEN
VALUES (1,'Hatchback'),
       (2,'Sedan'),
       (3,'SUV');

INSERT INTO LAIXE (MaLX,Ho,Dem,Ten,NgaySinh,SoGP,HanGP)
VALUES (1,'Nguyen','Van','Tung','2000-01-15','799876543210','2030-07-05'),
       (2,'Le','Quoc','Huy','1998-02-20','798765432109','2032-11-20');

INSERT INTO PHUONGTIEN
VALUES (2,1,'51E-135.75',2018,null,1),
       (3,2,'51E-482.36',2018,2,1);

INSERT INTO CALAMVIEC
VALUES (1,1,1,'2023-01-01 08:00:00','2023-01-01 16:00:00'),
       (2,2,2,'2023-01-02 10:00:00','2023-01-02 18:00:00');
